name: Android CI

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
jobs:

  peekCache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Peek Cache
        run: ls -a /home/runner

  buildDevelopApk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Build with Gradle
        run: ./gradlew --no-daemon assembleDebug -Dorg.gradle.jvmargs=-Xmx2048m
      - name: Archive assembled APK
        uses: actions/upload-artifact@v2
        with:
          name: assembled-develop-apk
          path: app/build/outputs/apk/develop/app-develop.apk

  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Run UnitTest
        run: ./gradlew --no-daemon testDebugUnitTest -Dorg.gradle.jvmargs=-Xmx2048m

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Run Android Lint
        run: ./gradlew --no-daemon lintDebug -Dorg.gradle.jvmargs=-Xmx2048m
